### ISSUE TITLE
FileNotFound errors and OBS freezing/crashing on fresh load

### ISSUE THREAD

**Issue by cr08** [pjw29/obs-rec-rename#1]
This has been mentioned by myself and another user on the OBS forums ( https://obsproject.com/forum/threads/obs-rec-rename.150978/ ) already but figured I'd post here as well to hopefully grab attention and probably in the correct spot as a proper 'Issue':

Fresh load of the plugin. Personally I've tried it with the latest available version of Python 3.6 and OBS v27 on Windows. Also tried the latest OBS v28 RC and Python 3.10. Even grabbed the specific linked pywin32 package from the README.

I've copied the screenshot another user posted but I can confirm seeing the exact same thing.

![image](https://user-images.githubusercontent.com/1199481/186259693-d7485069-9ebf-4719-8c34-d8b11424a817.png)

Ultimately as soon as the plugin is loaded in OBS starts acting funky with intermittent unresponsiveness but within seconds it'll eventually just freeze and cause me to force close it. Don't really get an opportunity to set any of the config options.

**Comment by pjw29** [comment]
Hi, my apologies I don't monitor the OBS forums and it doesn't seem to
notify my via email so GitHub seems a better place to contact me.

This plugin was never really designed for production which is why it was so
poorly documented. It was purely something that did what I needed
perfectly, with no guarantees it would even run for others.

That said happy to have a look into this over the next few days, would you
be able to send me a text copy of that error log, as I believe some of the
crucial information is missing from the side.

**Comment by cr08** [comment]
Sure thing. Here's a snippet from my log. It appears to just be this constantly repeating (it went on for about 10k lines in the log file when OBS only ran for about 15 seconds).

```
13:01:03.459: [obs-scripting]: Loaded python script: RecordingRenamer.py
13:01:03.459: [Python: RecordingRenamer.py] 0
13:01:03.461: [Python: RecordingRenamer.py] timer activated
13:01:03.461: [Python: RecordingRenamer.py] Processing files in 
13:01:03.461: [Python] Python failure in timer_call:440:
13:01:03.461: [Python: RecordingRenamer.py] Traceback (most recent call last):
13:01:03.461: [Python: RecordingRenamer.py]   File "C:/Users/Vchat/AppData/Roaming/obs-studio/scripts/obs-rec-rename-main\RecordingRenamer.py", line 148, in timer_process
13:01:03.462: [Python: RecordingRenamer.py]     rename_files(Data.OutputDir)
13:01:03.462: [Python: RecordingRenamer.py]   File "C:/Users/Vchat/AppData/Roaming/obs-studio/scripts/obs-rec-rename-main\RecordingRenamer.py", line 63, in rename_files
13:01:03.462: [Python: RecordingRenamer.py]     for txtfile in os.listdir(directory):
13:01:03.462: [Python: RecordingRenamer.py] FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
13:01:03.478: [Python: RecordingRenamer.py] timer activated
13:01:03.478: [Python: RecordingRenamer.py] Processing files in 
13:01:03.478: [Python] Python failure in timer_call:440:
13:01:03.478: [Python: RecordingRenamer.py] Traceback (most recent call last):
13:01:03.478: [Python: RecordingRenamer.py]   File "C:/Users/Vchat/AppData/Roaming/obs-studio/scripts/obs-rec-rename-main\RecordingRenamer.py", line 148, in timer_process
13:01:03.478: [Python: RecordingRenamer.py]     rename_files(Data.OutputDir)
13:01:03.478: [Python: RecordingRenamer.py]   File "C:/Users/Vchat/AppData/Roaming/obs-studio/scripts/obs-rec-rename-main\RecordingRenamer.py", line 63, in rename_files
13:01:03.478: [Python: RecordingRenamer.py]     for txtfile in os.listdir(directory):
13:01:03.478: [Python: RecordingRenamer.py] FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
13:01:03.495: [Python: RecordingRenamer.py] timer activated
13:01:03.495: [Python: RecordingRenamer.py] Processing files in 
13:01:03.495: [Python] Python failure in timer_call:440:
13:01:03.495: [Python: RecordingRenamer.py] Traceback (most recent call last):
13:01:03.495: [Python: RecordingRenamer.py]   File "C:/Users/Vchat/AppData/Roaming/obs-studio/scripts/obs-rec-rename-main\RecordingRenamer.py", line 148, in timer_process
13:01:03.495: [Python: RecordingRenamer.py]     rename_files(Data.OutputDir)
13:01:03.495: [Python: RecordingRenamer.py]   File "C:/Users/Vchat/AppData/Roaming/obs-studio/scripts/obs-rec-rename-main\RecordingRenamer.py", line 63, in rename_files
13:01:03.495: [Python: RecordingRenamer.py]     for txtfile in os.listdir(directory):
13:01:03.495: [Python: RecordingRenamer.py] FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
13:01:03.511: [Python: RecordingRenamer.py] timer activated
````

No huge rush but definitely appreciated either way. I think this is a VERY useful tool and kinda shows since EposVox highlighted it on his channel. Honestly something I think OBS should already have natively.

**Comment by pjw29** [comment]
Cheers for that. I have a week off from my day job from tomorrow so plan to
look at it then. Would you also be able to screen shot the configuration
you are using for the script within OBS? One of the errors points to
something being blank, it also looks like it's firing the timer way too
much but hard to tell why form my first glance.

I didn't know the script was featured. It was really just one of those
things I had been super irritated by for years with OBS and kept finding
myself switching back to Shadow play, but hating the lack of flexibility so
was left with 1 choice, fix OBS. I just bit the bullet and coded it myself
(I am not a great coder), and hoped.it would work for me, and if possible a
few others could fix the same niggle.

**Comment by cr08** [comment]
Unfortunately looks like it's interfering with me being able to capture a screenshot (somehow with it acting up I'm either getting a screenshot of a different window or my desktop background), but all fields are blank by default except for the time interval which is listed as 15s. And it doesn't give much time to really adjust anything.

I did try for the heck of it to manually add my specified directory to the OutputDir string but looks it doesn't change anything and when I was able to open the script page in OBS the directory field was still blank. 

````
class Data:
    OutputDir = 'C:\\Users\\Vchat\\Videos'
````

Also, here's where it was featured: https://www.youtube.com/watch?v=f0hQMDoK7sU&list=PLzo7l8HTJNK9Da8hio8V8NvmFOhUluj10&index=6&t=342s

**Comment by ntoff** [comment]
Delay is initially 0 (zero) so the script just goes ham every zero seconds

giving Data.Delay the value of "period" OR an initial value of 15000 for 15 seconds seems to fix the freeze on load issue for me.
`Data.Delay = 1000*S.obs_data_get_int(settings,"period") or 15000`

**Comment by cr08** [comment]
Awesome. Very much appreciated. I almost forgot about this myself. But that quick modification seems to have completely fixed this.

**Comment by pjw29** [comment]
Hi all, my apologies for never getting the chance to look into this, things snowballed in August when I had hoped to, but it looks like the fix suggested has worked, I ran a few tests and have made the change into main. Thanks @ntoff and @cr08 for all your help on this one. Closing as fixed. https://github.com/pjw29/obs-rec-rename/commit/a1016d84b3d215a574a45dbfa0ddcaeaec63020a
